location: .gitman
sources:
  - repo: https://github.com/klaxalk/subrepo1
    name: subrepo1
    rev: master
    type: git
    sparse_paths:
      -
    link: subrepo1
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/klaxalk/subrepo2
    name: subrepo2
    rev: master
    type: git
    sparse_paths:
      -
    link: subrepo2
    links:
      -
    scripts:
      - git submodule update --init --recursive
